version: '3.8'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    container_name: 'myapp'
    volumes:
      - .:/app
    environment:
      - DEBUG=1
    # command: python manage.py runserver 0.0.0.0:8000  # Optional: override CMD in Dockerfile
